import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'
import Nav from './component/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet" /> */}
      </head>
      <body className={inter.className}>
      {/* <Nav /> */} 
        {children}
        </body>
    </html>
  )
}
